# run again.  Do not edit this file unless you know what you are doing.
from PySide6 import QtWidgets, QtCore
from PySide6.QtCore import QMetaObject, QRect, QSize, Qt
from PySide6.QtGui import QIcon
from PySide6.QtWidgets import QLabel, QLineEdit, QPlainTextEdit, QPushButton, QSizePolicy, QDialog

from videotrans.configure.config import tr, ROOT_DIR
from videotrans.util.help_misc import show_refaudio_win, open_url


class Ui_fishtts(QDialog):
    def __init__(self):
        super().__init__()
        self.setWindowIcon(QIcon(f"{ROOT_DIR}/videotrans/styles/icon.ico"))
        self.setupUi(self)
    def setupUi(self, fishttsform):
        self.has_done = False
        if not fishttsform.objectName():
            fishttsform.setObjectName("fishttsform")
        fishttsform.setWindowModality(Qt.NonModal)
        fishttsform.resize(600, 250)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(fishttsform.sizePolicy().hasHeightForWidth())
        fishttsform.setSizePolicy(sizePolicy)
        fishttsform.setMaximumSize(QSize(600, 250))

        v1 = QtWidgets.QVBoxLayout(fishttsform)

        self.label = QLabel(fishttsform)
        self.label.setObjectName("label")
        self.label.setMinimumSize(QSize(0, 35))
        self.api_url = QLineEdit(fishttsform)
        self.api_url.setObjectName("api_url")
        self.api_url.setMinimumSize(QSize(0, 35))
        h1 = QtWidgets.QHBoxLayout()
        h1.addWidget(self.label)
        h1.addWidget(self.api_url)
        v1.addLayout(h1)


        self.label_5 = QLabel(fishttsform)
        self.label_5.setObjectName("label_5")
        self.label_5.setText(tr('API request instructions'))
        v1.addWidget(self.label_5)

        self.tips = QPlainTextEdit(fishttsform)
        self.tips.setObjectName("tips")
        self.tips.setMinimumHeight(150)
        self.tips.setReadOnly(True)
        v1.addWidget(self.tips)

        h2 = QtWidgets.QHBoxLayout()

        self.save = QPushButton(fishttsform)
        self.save.setObjectName("save")
        self.save.setGeometry(QRect(10, 450, 93, 35))
        self.save.setMinimumSize(QSize(0, 35))

        self.test = QPushButton(fishttsform)
        self.test.setObjectName("test")
        self.test.setGeometry(QRect(490, 450, 93, 35))
        self.test.setMinimumSize(QSize(0, 35))

        help_btn = QtWidgets.QPushButton()
        help_btn.setMinimumSize(QtCore.QSize(0, 35))
        help_btn.setObjectName("help_btn")
        help_btn.setCursor(Qt.PointingHandCursor)
        help_btn.setText(tr("Fill out the tutorial"))
        help_btn.clicked.connect(lambda: open_url(url='https://pyvideotrans.com/fishtts'))

        h2.addWidget(self.save)
        h2.addWidget(self.test)

        ref_btn = QtWidgets.QPushButton()
        ref_btn.setText(tr("Set reference audio"))
        ref_btn.clicked.connect(show_refaudio_win)
        h2.addWidget(ref_btn)
        h2.addWidget(help_btn)
        v1.addLayout(h2)

        self.retranslateUi(fishttsform)

        QMetaObject.connectSlotsByName(fishttsform)

    # setupUi

    def retranslateUi(self, fishttsform):
        tips = tr('fish_tts_api_help')

        fishttsform.setWindowTitle("Fish-speech API " +tr('This channel needs deployed and started before available'))
        self.tips.setPlainText(tips)
        self.save.setText(tr("Save"))
        self.api_url.setPlaceholderText(tr('fish_tts_api_url_hint'))
        self.label.setText("Fish-speech API")
        self.test.setText(tr("Test"))
