# run again.  Do not edit this file unless you know what you are doing.
from PySide6 import QtWidgets, QtCore
from PySide6.QtCore import QMetaObject, QSize, Qt
from PySide6.QtGui import QIcon
from PySide6.QtWidgets import QLabel, QLineEdit, QPlainTextEdit, QPushButton, QSizePolicy, QHBoxLayout, QVBoxLayout, \
    QCheckBox, QDialog

from videotrans.configure.config import tr,ROOT_DIR
from videotrans.util.help_misc import open_url


class Ui_gptsovits(QDialog):
    def __init__(self):
        super().__init__()
        self.setWindowIcon(QIcon(f"{ROOT_DIR}/videotrans/styles/icon.ico"))
        self.setupUi(self)
    def setupUi(self, gptsovitsform):
        self.has_done = False
        if not gptsovitsform.objectName():
            gptsovitsform.setObjectName("gptsovitsform")
        gptsovitsform.setWindowModality(Qt.NonModal)
        gptsovitsform.resize(800, 500)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(gptsovitsform.sizePolicy().hasHeightForWidth())
        gptsovitsform.setSizePolicy(sizePolicy)
        gptsovitsform.setMaximumSize(QSize(800, 500))

        self.wrap_h = QHBoxLayout(gptsovitsform)
        self.wrap_h.setObjectName(u"wrap_h")
        self.inner_v = QVBoxLayout()

        h1 = QHBoxLayout()
        self.label = QLabel()
        self.label.setObjectName("label")
        self.label.setMinimumSize(QSize(0, 35))
        self.api_url = QLineEdit()
        self.api_url.setObjectName("api_url")
        self.api_url.setMinimumSize(QSize(0, 35))
        h1.addWidget(self.label)
        h1.addWidget(self.api_url)
        self.inner_v.addLayout(h1)


        self.label_4 = QLabel()
        self.label_4.setObjectName("label_4")
        self.label_4.setMinimumSize(QSize(301, 16))
        self.label_4.setText(tr('gptsovits_reference_format'))

        self.role = QPlainTextEdit()
        self.role.setObjectName("role")
        self.role.setMinimumSize(QSize(771, 100))
        self.role.setReadOnly(False)
        self.inner_v.addWidget(self.label_4)
        self.inner_v.addWidget(self.role)

        h3 = QHBoxLayout()
        self.is_v2 = QCheckBox()
        self.is_v2.setText("api_v2?")
        self.is_v2.setToolTip(tr('gptsovits_api_v2_hint'))
        self.save = QPushButton()
        self.save.setObjectName("save")
        self.save.setMinimumSize(QSize(0, 35))
        h3.addWidget(self.is_v2)
        h3.addWidget(self.save)
        self.test = QPushButton()
        self.test.setObjectName("test")
        self.test.setMinimumSize(QSize(0, 35))
        help_btn = QtWidgets.QPushButton()
        help_btn.setMinimumSize(QtCore.QSize(0, 35))
        help_btn.setObjectName("help_btn")
        help_btn.setCursor(Qt.PointingHandCursor)
        help_btn.setText(tr("Fill out the tutorial"))
        help_btn.clicked.connect(lambda: open_url(url='https://pyvideotrans.com/gptsovits'))

        h3.addWidget(self.test)
        h3.addWidget(help_btn)
        self.inner_v.addLayout(h3)

        # end
        self.wrap_h.addLayout(self.inner_v)

        self.retranslateUi(gptsovitsform)

        QMetaObject.connectSlotsByName(gptsovitsform)

    # setupUi

    def retranslateUi(self, gptsovitsform):
        gptsovitsform.setWindowTitle("GPT-SoVITS API "+tr('This channel needs deployed and started before available'))
        self.role.setPlaceholderText(tr('gptsovits_reference_hint'))
        self.save.setText(tr("Save"))
        self.api_url.setPlaceholderText(tr('gptsovits_api_url_hint'))
        self.label.setText("API URL")
        self.test.setText(tr("Test"))
    # retranslateUi
