# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtWidgets
from PySide6.QtCore import Qt
from PySide6.QtGui import QIcon
from PySide6.QtWidgets import QPlainTextEdit, QDialog

from videotrans.configure.config import tr, ROOT_DIR
from videotrans.util.help_misc import open_url


class Ui_recognapi(QDialog):
    def __init__(self):
        super().__init__()
        self.setWindowIcon(QIcon(f"{ROOT_DIR}/videotrans/styles/icon.ico"))
        self.setupUi(self)
    def setupUi(self, recognapiform):
        self.has_done = False
        recognapiform.setObjectName("recognapiform")
        recognapiform.setWindowModality(QtCore.Qt.NonModal)
        recognapiform.resize(500, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(recognapiform.sizePolicy().hasHeightForWidth())
        recognapiform.setSizePolicy(sizePolicy)

        self.verticalLayout = QtWidgets.QVBoxLayout(recognapiform)
        self.verticalLayout.setObjectName("verticalLayout")

        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(recognapiform)

        self.label.setMinimumSize(QtCore.QSize(100, 35))
        self.label.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")

        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.recognapiform_address = QtWidgets.QLineEdit(recognapiform)
        self.recognapiform_address.setMinimumSize(QtCore.QSize(210, 35))
        self.recognapiform_address.setObjectName("recognapiform_address")

        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.recognapiform_address)
        self.verticalLayout.addLayout(self.formLayout_2)

        # sk
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.formLayout_3.setObjectName("formLayout_3")
        self.labelkey = QtWidgets.QLabel(recognapiform)
        self.labelkey.setMinimumSize(QtCore.QSize(100, 35))
        self.labelkey.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.labelkey.setObjectName("label")

        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelkey)
        self.recognapiform_key = QtWidgets.QLineEdit(recognapiform)
        self.recognapiform_key.setMinimumSize(QtCore.QSize(210, 35))
        self.recognapiform_key.setObjectName("recognapiform_key")

        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.recognapiform_key)
        self.verticalLayout.addLayout(self.formLayout_3)

        self.set = QtWidgets.QPushButton(recognapiform)
        self.set.setMinimumSize(QtCore.QSize(0, 35))
        self.set.setObjectName("set")

        self.test = QtWidgets.QPushButton(recognapiform)
        self.test.setMinimumSize(QtCore.QSize(0, 30))
        self.test.setObjectName("test")

        help_btn = QtWidgets.QPushButton()
        help_btn.setMinimumSize(QtCore.QSize(0, 35))
        help_btn.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        help_btn.setObjectName("help_btn")
        help_btn.setCursor(Qt.PointingHandCursor)
        help_btn.setText(tr("Fill out the tutorial"))
        help_btn.clicked.connect(lambda: open_url(url='https://pyvideotrans.com/recognapi'))

        self.ask = QPlainTextEdit(recognapiform)
        self.ask.setMinimumSize(QtCore.QSize(0, 200))
        self.ask.setReadOnly(True)
        self.verticalLayout.addWidget(self.ask)

        self.layout_btn = QtWidgets.QHBoxLayout()
        self.layout_btn.setObjectName("layout_btn")

        self.layout_btn.addWidget(self.set)
        self.layout_btn.addWidget(self.test)
        self.layout_btn.addWidget(help_btn)

        self.verticalLayout.addLayout(self.layout_btn)

        self.retranslateUi(recognapiform)
        QtCore.QMetaObject.connectSlotsByName(recognapiform)

    def retranslateUi(self, recognapiform):
        recognapiform.setWindowTitle(tr("Custom Speech Recognition API"))

        self.label.setText(tr("API"))
        self.labelkey.setText(tr("Password/Token"))
        tips = tr('recognapi_help')
        self.ask.setPlainText(tips)
        self.recognapiform_address.setPlaceholderText('')
        self.set.setText(tr("Save"))
        self.test.setText(tr("Test"))
