# run again.  Do not edit this file unless you know what you are doing.
import re
from pathlib import Path
from typing import List

from PySide6 import QtCore, QtWidgets
from PySide6.QtGui import Qt, QIcon
from PySide6.QtWidgets import QFileDialog
from videotrans.configure.config import ROOT_DIR, tr, app_cfg, settings, defaulelang
from videotrans.configure.constants import LANG_CODE, Whisper_Models

# ultrafast 、 superfast 、 veryfast 、 faster 、 fast 、 medium （默认）、 slow和veryslow
# 处理速度越来越慢，输出视频压缩率和质量越来越高，视频尺寸也将变小

# 中文注释 界面ui控制
from videotrans.translator import LLM_CONCERT_MAP
from videotrans.util.help_misc import open_url

prompt_dicts={}
for code in LANG_CODE.keys():
    if code == 'auto':
        continue
    prompt_dicts[f'initial_prompt_{code}']=tr('Initial prompt for the Whisper model for speech',tr(code))

notices = {
    "common": {
        "lang": "Set the software's interface language. Requires a restart to take effect.",
        "countdown_sec": "Countdown in seconds for a single video translation.",
        "homedir": "Directory to save results (STT, TTS, TransSubtitles). Defaults to the 'output' folder.",

        "retry_nums": "Number of retries after failure",

        "llm_chunk_size": "When LLM Correction errors in the LLM large model, the number of subtitles sent each time is important. A larger value results in better sentence segmentation. Sending all subtitles at once is optimal, but this is limited by the maximum output token and context (max_token). An excessively long input may exceed the AI  limit and fail. The default is 20 subtitles.",
        "llm_ai_type": "AI provider for LLM Correction errors",

        "dont_notify": "Disable desktop notifications for task completion or failure.",

        "noise_separate_nums": "The more threads used for separation of human and background voices, the faster the process, but the more resources it consumes.",
        "uvr_models": "Select the model used when separating background noise.",

        "batch_nums": "When translating in batches, set the number of lines to translate simultaneously in each batch here.",
        "show_more_settings": "To avoid confusion caused by too many parameters, most parameters are hidden by default on the main interface. Selecting this option will switch to displaying all parameters by default.",

        "process_max": "Process Maximum for CPU",
        "process_max_gpu": "The number of GPU tasks that can be executed simultaneously should be set to 1 unless video memory very large",
        "device_name":"Force the operation of heavy-duty equipment; do not tamper with it unless you know what you are doing.",
        "bit8":"8-bit quantization is used for qwen3-tts to reduce video memory usage."

    },
    "video": {
        "crf": "Constant Rate Factor (CRF) for video quality. 0=lossless (huge file), 51=low quality (small file).",
        "preset": "Controls the encoding speed vs. quality balance (e.g., ultrafast, medium, slow). Faster means larger files.",
        "video_codec": "Video codec: libx264 (better compatibility) or libx265 (higher compression).",
        "out_video_ext": "Output video format (mp4/mkv)",
        "fps_mode": "When there is slow-motion video processing, variable frame rate (VRF) works better, while fixed frame rate (CFR) has better compatibility.",

        "force_lib": "Force software encoding (slower but more compatible). Hardware encoding is preferred by default.",
        "hw_decode": "When compositing videos, prioritize hard decoding; it's fast but prone to errors.",
        "ffmpeg_cmd": "Custom FFmpeg command arguments, added before the output file argument.",
    },
    "whisper": {
        "vad_type": "Select VAD",
        "threshold": "VAD: Minimum probability for an audio chunk to be considered speech.",
        "no_speech_threshold": "no speech threshold",
        "max_speech_duration_s": "VAD: Maximum duration (s) of a single speech segment before splitting.",
        "min_speech_duration_ms": "If a subtitle's duration is less than this value in milliseconds, attempt to merge it into an adjacent subtitle.",
        "min_silence_duration_ms": "VAD: Minimum silence duration (ms) to mark the end of a segment.",
        "model_for_recogn2":"The model used for secondary recognition (always using the Faster-Whisper channel)",

        "max_speech_duration_s2": "Maximum speech duration (seconds) during secondary recognition. Limits the maximum length of a single speech segment. Forced segmentation occurs if this length is exceeded. Enter a number in seconds.",
        "min_speech_duration_ms2": "Shortest speech duration (milliseconds) during secondary recognition. If a subtitle's duration is less than this value in milliseconds, attempt to merge it into an adjacent subtitle. Unit: milliseconds.",


        "speaker_type": "The model used for speaker separation. The default is the built-in model, supporting both Chinese and English. Pyannote is optional. \nIf selected, you must have a token from \nhttps://huggingface.co \nand agree to the Pyannote licensing agreement. \nFor details, please visit the URL for a tutorial: \nhttps://pvt9.com/shuohuaren",
        "hf_token": "Enter your token from huggingface.co. Otherwise, you cannot use Pyannote speaker separation. \nFor details, please see the tutorial: \nhttps://pvt9.com/shuohuaren",

        "cuda_com_type": "Compute type for faster-whisper (e.g., int8, float16, float32).",
        "beam_size": "Beam size for transcription (1-5). Higher is more accurate but uses more VRAM.",
        "best_of": "Best-of for transcription (1-5). Higher is more accurate but uses more VRAM.",
        "condition_on_previous_text": "Condition on previous text for better context (uses more GPU, may cause repetition).",
        "temperature": "temperature",
        "repetition_penalty": "Increasing this value helps reduce repetitions",
        "compression_ratio_threshold": "Decrease this value helps reduce repetitions",
        "hotwords": "hotwords",

        "model_list": "Comma-separated list of model names for faster-whisper modes.",
        "Whisper_cpp_models": "Comma-separated list of model names for whisper.cpp mode.",
        "gemini_recogn_chunk": "Number of audio slices per request for Gemini recognition. Larger values improve accuracy but increase failure rate.",
        "zh_hant_s": "Force conversion of recognized Traditional Chinese to Simplified Chinese.",
        "del_end_punc": "Remove punctuation at the end of subtitles?",
        "asr_wait": "The number of seconds the cloud API pauses after each recognition to prevent exceeding the frequency limit."

    },
    "trans": {
        "trans_thread": "Number of subtitle lines per request for traditional translation.",
        "aitrans_thread": "Number of subtitle lines per request for AI translation.",
        "translation_wait": "Delay (in seconds) between translation requests to prevent rate-limiting.",
        "aisendsrt": "Send full SRT format content when using AI translation.",
        "aitrans_temperature": "AI models temperature,default is 1.0",
        "aitrans_context": "The AI ​​translation channel includes all original subtitles for reference."
    },
    "dubbing": {
        "dubbing_thread": "Number of concurrent threads for dubbing.",
        "dubbing_wait": "Delay (in seconds) between dubbing requests to prevent rate-limiting.",
        "remove_dubb_silence": "Remove the mute buffer before and after each subtitle audio. Selecting this option will improve audio-visual synchronization, but may make the ending feel rushed.",
        "save_segment_audio": "Save the dubbed audio for each individual subtitle line.",
        "normal_text": "Text normalization before dubbing",
        "edgetts_max_concurrent_tasks": "The higher the concurrent voice-over capacity of the EdgeTTS channel, the faster the speed, but rate throttling may fail.",
        "edgetts_retry_nums": "Number of retries after EdgeTTS channel failure",
        "chattts_voice": "ChatTTS voice timbre value.",

    },
    "justify": {

        "max_audio_speed_rate": "Maximum audio speed-up rate. Default: 100.",
        "max_video_pts_rate": "Maximum video slow-down rate. Default: 10 (cannot exceed 10).",
        "cjk_len": "Number of characters per line for Chinese, Japanese, and Korean subtitles; more than this will result in a line break",
        "other_len": "Number of words per line for subtitles in other languages; more than this will result in a line break"
    },

    "prompt_init": {}
}

titles = {
    "cjk_len": "Number of characters per line for CJK",
    "other_len": "Number of words per line for Other",
    "bit8":"8-bit quantization for qwen3-tts",
    "process_max": "Number of CPU tasks[restart]",
    "process_max_gpu": "Number of GPU tasks[restart]",
    "device_name":"Force the operation of heavy-duty equipment",
    "max_audio_speed_rate": "Maximum audio speed-up rate",
    "max_video_pts_rate": "Maximum video slow-down rate",
    "batch_nums": "Translating batches, quantity per batch",
    "dont_notify": "Disable desktop notifications",
    "llm_ai_type": "AI provider for LLM Correction errors",
    "prompt_init": "Whisper model initial prompt",
    "gemini_recogn_chunk": "Gemini speech recognition batch slice count",
    "llm_chunk_size": "LLM Correction errors How many subtitles are sent each time",
    "hw_decode": "ffmpeg decode video use cuda",
    "ai302_models": "302.AI translation models",
    "ai302tts_models": "302.AI-TTS models",
    "aitrans_temperature": "AI temperature for translation subtitles",
    "aitrans_context": "AI ​​translation includes all original subtitles for reference?",
    "no_speech_threshold": "no speech threshold",
    "temperature": "temperature",
    "hotwords": "hotwords",
    "remove_dubb_silence": "Remove the mute buffer each subtitle audio",
    "normal_text": "Text Text normalization",
    "uvr_models": "BGM separation model",
    "del_end_punc": "Remove punctuation at end subtitles?",
    "out_video_ext": "Output video format (mp4/mkv)",

    "model_for_recogn2":"The model used for secondary recognition",

    "asr_wait": "Cloud API pauses after each recognition/Seconds",

    "retry_nums": "Number of retries after failure",
    "fps_mode": "Variable frame rate (vfr)/fixed frame rate (cfr)",

    "repetition_penalty": "repetition penalty",
    "compression_ratio_threshold": "compression ratio threshold",

    "vad_type": "Select VAD",

    "speaker_type": "Model for speaker separation",

    "hf_token": "Your token from huggingface.co",

    "show_more_settings": "Show all parameters?",

    "edgetts_max_concurrent_tasks": "The higher concurrent of EdgeTTS",
    "edgetts_retry_nums": "Retries after EdgeTTS failure",

    "noise_separate_nums": "Threads nums for separation",
    "openairecognapi_model": "OpenAI speech recognition model",
    "chatgpt_model": "ChatGPT model list",
    "openaitts_model": "OpenAI TTS model list",
    "azure_model": "Azure model list",
    "localllm_model": "Local LLM model list",
    "zijiehuoshan_model": "ByteDance Volcano Engine inference endpoint",
    "model_list": "faster-whisper models",
    "Whisper_cpp_models": "whisper.cpp models",
    "homedir": "Set output directory",
    "lang": "Software interface language",
    "save_segment_audio": "Save dubbed audio for each subtitle line",
    "crf": "Video output quality control (CRF)",
    "force_lib": "Force software video encoding?",
    "preset": "Output video compression preset",
    "ffmpeg_cmd": "Custom FFmpeg command arguments",
    "video_codec": "H.264/H.265 encoding",
    "threshold": "VAD: Speech probability threshold",
    "max_speech_duration_s": "VAD:max speech duration(s)",
    "min_speech_duration_ms": "VAD:min speech duration(ms)",

    "max_speech_duration_s2": "Recognition(2): max speech duration(s)",
    "min_speech_duration_ms2": "Recognition(2): min speech duration(ms)",

    "min_silence_duration_ms": "VAD:Min silence duration for split(ms)",
    "trans_thread": "Batch size (lines) for traditional translation",
    "aitrans_thread": "Batch size (lines) for AI translation",
    "dubbing_thread": "Concurrent dubbing threads",
    "countdown_sec": "Countdown for single video translation pause",
    "backaudio_volume": "Background audio volume multiplier",
    "loop_backaudio": "Loop background audio",
    "cuda_com_type": "Compute data type",
    "beam_size": "Recognition accuracy (beam_size)",
    "best_of": "Recognition accuracy (best_of)",
    "condition_on_previous_text": "Enable context awareness",
    "zh_hant_s": "Convert Traditional to Simplified Chinese subtitles",
    "chattts_voice": "ChatTTS voice timbre value",
    "translation_wait": "Pause (s) after each translation request",
    "dubbing_wait": "Pause (s) after each dubbing request",
    "gemini_model": "Gemini model list",
    "aisendsrt": "Send full SRT format for AI translation",
}

heads = {
    "common": "General",
    "video": "Video Output",
    "whisper": "ASR Settings",
    "justify": "Alignment",
    "trans": "Translation",
    "dubbing": "Dubbing",
    "prompt_init": "Whisper Prompt"
}

if defaulelang == 'vi_VN':
    notices = {
        section: {key: tr(value) for key, value in values.items()}
        for section, values in notices.items()
    }
    titles = {key: tr(value) for key, value in titles.items()}
    heads = {key: tr(value) for key, value in heads.items()}


titles.update(prompt_dicts)
notices['prompt_init'].update(prompt_dicts)

class Ui_setini(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowIcon(QIcon(f"{ROOT_DIR}/videotrans/styles/icon.ico"))
        self.setupUi(self)


    def get_target(self):
        dirname = QFileDialog.getExistingDirectory(self, tr('selectsavedir'), Path.home().as_posix())
        if dirname:
            dirpath = Path(dirname)
            HOME_DIR = dirpath.as_posix()
            settings['homedir'] = HOME_DIR
            self.homedir_btn.setText(HOME_DIR)
            settings.save()

    def _is_comboBox(self,key):
        return key in ['cuda_com_type','llm_ai_type','vad_type','speaker_type','video_codec','preset','lang','uvr_models','out_video_ext',"fps_mode","device_name","model_for_recogn2"]

    def _get_comboBox(self,key) -> List[str]:
        data = {
            "cuda_com_type": [
                'default',
                'auto',
                'int8',
                'int16',
                'float16',
                'float32',
                'bfloat16',
                'int8_float16',
                'int8_float32',
                'int8_bfloat16'
            ],
            "fps_mode":["vfr","cfr"],
            "llm_ai_type": list(LLM_CONCERT_MAP.values()),
            "vad_type": ['tenvad', 'silero'],
            "speaker_type": ['built', 'ali_CAM', 'pyannote'],
            "video_codec": ['264', '265'],
            "preset": ['ultrafast', 'superfast', 'veryfast', 'faster', 'fast', 'medium', 'slow', 'slower',
                       'veryslow'],
            "lang": list(app_cfg.SUPPORT_LANG.keys()),
            "uvr_models": [
                'spleeter',
                'UVR-MDX-NET-Inst_HQ_4',
                'UVR-MDX-NET-Inst_HQ_1',
                'UVR-MDX-NET-Inst_HQ_2',
                'UVR-MDX-NET-Inst_HQ_3',
                'UVR-MDX-NET-Inst_HQ_5',
                'UVR-MDX-NET-Inst_Main',
                'UVR-MDX-NET-Inst_1',
                'UVR-MDX-NET-Inst_2',
                'UVR-MDX-NET-Inst_3'
            ],
            "out_video_ext": ['.mp4', '.mkv'],
            "device_name":['auto','cuda','cpu','mps','xpu','cuda:0','cuda:1','cuda:2','cuda:3'],
            "model_for_recogn2":Whisper_Models.split(',')
        }

        return data.get(key, [""])

    def _build_setting_row(self, key, tips_str, parent_layout):
        """构建单行设置项（标签按钮 + 输入控件）并添加到 parent_layout"""
        tmp = QtWidgets.QHBoxLayout()
        tmp_0 = QtWidgets.QPushButton()
        tmp_0.setStyleSheet("""background-color:transparent;""")

        tmp_0.setText(titles[key])
        tmp_0.setObjectName(f'btn_{key}')
        tmp_0.setToolTip(tips_str)
        tmp.addWidget(tmp_0)

        val = str(settings.get(key, ""))
        # 下拉列表 comboBox
        if self._is_comboBox(key):
            combobox_data = self._get_comboBox(key)
            tmp1 = QtWidgets.QComboBox()
            tmp1.addItems(combobox_data)

            if key=='llm_ai_type':
                tmp1.setCurrentIndex(int(float(val)) if re.match(r'^\d+$',val) else 0 )
            elif val in combobox_data:
                tmp1.setCurrentText(val)
            tmp1.setObjectName(key)
            tmp1.setToolTip(tips_str)
            tmp.addWidget(tmp1)
            tmp.addStretch(1)
            parent_layout.addLayout(tmp)
            return
        # 设置家目录按钮
        if key == 'homedir':
            self.homedir_btn = QtWidgets.QPushButton()
            self.homedir_btn.setCursor(Qt.PointingHandCursor)
            self.homedir_btn.setText(str(val))
            self.homedir_btn.setToolTip(
                tr("Click on Set Home Directory to save the result files for video separation, subtitle translation, subtitle dubbing, etc."))
            self.homedir_btn.clicked.connect(self.get_target)
            self.homedir_btn.setObjectName(key)
            tmp.addWidget(self.homedir_btn)
            tmp.addStretch(1)
            parent_layout.addLayout(tmp)
            return
        # 是checkbox 复选框
        if val.lower() in ['true', 'false']:
            tmp_1 = QtWidgets.QCheckBox()
            tmp_1.setChecked(True if val.lower() == 'true' else False)
            tmp_1.setToolTip(tips_str)
            tmp_1.setObjectName(key)

            tmp.addWidget(tmp_1)
            tmp.addStretch(1)
            parent_layout.addLayout(tmp)
            return

        # 是 model_list faster-whisper
        if key in ['model_list', 'Whisper_cpp_models']:
            tmp_1 = QtWidgets.QPlainTextEdit()
            tmp_1.setPlainText(val)
            tmp_1.setToolTip(tips_str)
            tmp_1.setObjectName(key)
            tmp.addWidget(tmp_1)
            parent_layout.addLayout(tmp)
            return

        # 普通文本框 字符串或数字
        tmp_1 = QtWidgets.QLineEdit()
        tmp_1.setMinimumSize(QtCore.QSize(0, 30))
        tmp_1.setText(str(val))
        tmp_1.setPlaceholderText(tips_str)
        tmp_1.setToolTip(tips_str)
        tmp_1.setObjectName(key)
        tmp.addWidget(tmp_1)

        parent_layout.addLayout(tmp)

    def setupUi(self, setini):
        self.centralwidget = QtWidgets.QWidget(setini)
        self.centralwidget.setObjectName("centralwidget")
        self.has_done = False
        setini.setObjectName("setini")
        setini.setMinimumSize(900, 670)
        self.setWindowFlags(Qt.WindowStaysOnTopHint)
        self.layout = QtWidgets.QVBoxLayout(setini)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.layout.setObjectName("layout")

        action_layout = QtWidgets.QHBoxLayout()
        # 顶部提示文字
        label_title = QtWidgets.QLabel()
        label_title.setText(
            tr("Clicking  title on the left will show help"))
        label_title.setObjectName("label_head")
        label_title.setAlignment(Qt.AlignCenter)
        label_title.setStyleSheet("""color:#eeeeee;text-align:center;font-size:16px;margin-top:10px""")
        self.layout.addWidget(label_title)

        self.homedir_btn = None

        # 使用 QTabWidget 替代原来的双列滚动布局，每个模块一个标签卡
        self.tab_widget = QtWidgets.QTabWidget()
        self.tab_widget.setObjectName("tab_widget")
        self.tab_widget.setStyleSheet("""
            QTabWidget::pane {
                border: 1px solid #3a3a3a;
                background-color: #2b2b2b;
            }
            QTabBar::tab {
                background-color: #3a3a3a;
                color: #cccccc;
                padding: 8px 18px;
                margin-right: 2px;
                border-top-left-radius: 4px;
                border-top-right-radius: 4px;
                font-size: 13px;
            }
            QTabBar::tab:selected {
                background-color: #148CD2;
                color: #ffffff;
                font-weight: bold;
            }
            QTabBar::tab:hover:!selected {
                background-color: #4a4a4a;
            }
        """)

        for headkey, item in notices.items():
            # 每个标签页内部使用滚动区域，防止内容溢出
            tab_scroll = QtWidgets.QScrollArea()
            tab_scroll.setWidgetResizable(True)
            tab_scroll.setAlignment(Qt.AlignmentFlag.AlignTop)
            tab_scroll.setStyleSheet("QScrollArea{border:none;background-color:transparent;}")

            tab_content = QtWidgets.QWidget()
            tab_layout = QtWidgets.QVBoxLayout(tab_content)
            tab_layout.setContentsMargins(10, 10, 10, 10)

            for key, tips_str in item.items():
                self._build_setting_row(key, tips_str, tab_layout)

            tab_layout.addStretch()
            tab_scroll.setWidget(tab_content)
            self.tab_widget.addTab(tab_scroll, heads[headkey])

        # stretch=1 让 tab_widget 填充剩余空间，按钮固定在底部不会遮挡内容
        self.layout.addWidget(self.tab_widget, stretch=1)

        self.set_ok = QtWidgets.QPushButton()
        self.set_ok.setMinimumSize(QtCore.QSize(160, 40))
        self.set_ok.setObjectName("set_ok")
        self.set_ok.setCursor(Qt.PointingHandCursor)
        self.set_ok.setStyleSheet("""
            QPushButton {
                color: #ffffff;
                background-color: #148CD2;
                font-size: 15px;
                font-weight: bold;
                border-radius: 5px;
                padding: 6px 24px;
            }
            QPushButton:hover {
                background-color: #0e6fa0;
            }
            QPushButton:pressed {
                background-color: #0b5a82;
            }
        """)

        self.help_btn = QtWidgets.QPushButton()
        self.help_btn.setObjectName("help_btn")
        self.help_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.help_btn.setMaximumSize(QtCore.QSize(160, 30))
        self.help_btn.setCursor(Qt.PointingHandCursor)
        self.help_btn.setStyleSheet("""
            QPushButton {
                color: #aaaaaa;
                background-color: transparent;
                font-size: 12px;
                border: 1px solid #555555;
                border-radius: 4px;
                padding: 4px 12px;
            }
            QPushButton:hover {
                color: #ffffff;
                border-color: #148CD2;
            }
        """)
        self.help_btn.setText(tr("Fill out the tutorial"))
        self.help_btn.clicked.connect(lambda: open_url(url='https://pyvideotrans.com/adv'))

        action_layout.addStretch()
        action_layout.addWidget(self.set_ok)
        action_layout.addWidget(self.help_btn)
        action_layout.addStretch()

        self.layout.addLayout(action_layout)

        self.retranslateUi(setini)
        QtCore.QMetaObject.connectSlotsByName(setini)

    def update_ui(self):
        obj = self.findChild(QtWidgets.QComboBox, 'lang')
        current_text = obj.currentText()
        _support = {}
        for it in Path(f'{ROOT_DIR}/videotrans/language').glob('*.json'):
            if it.stat().st_size > 0:
                _support[it.stem] = it.as_posix()
        # 有变化时
        if _support and _support.keys() != app_cfg.SUPPORT_LANG.keys():
            app_cfg.SUPPORT_LANG = _support
            obj.clear()
            obj.addItems(list(_support.keys()))
            if current_text in _support:
                obj.setCurrentText(current_text)

    def retranslateUi(self, setini):
        setini.setWindowTitle(tr("Options"))
        self.set_ok.setText(tr("Save and Close"))
