# run again.  Do not edit this file unless you know what you are doing.
from PySide6 import QtWidgets, QtCore
from PySide6.QtCore import QMetaObject, QSize, Qt
from PySide6.QtGui import QIcon
from PySide6.QtWidgets import QLabel, QLineEdit, QPushButton, QSizePolicy, QDialog

from videotrans.configure.config import tr, ROOT_DIR
from videotrans.util.help_misc import open_url


class Ui_transapi(QDialog):
    def __init__(self):
        super().__init__()
        self.setWindowIcon(QIcon(f"{ROOT_DIR}/videotrans/styles/icon.ico"))
        self.setupUi(self)
    def setupUi(self, transapiform):
        self.has_done = False
        if not transapiform.objectName():
            transapiform.setObjectName("transapiform")
        transapiform.setWindowModality(Qt.NonModal)
        transapiform.resize(600, 400)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(transapiform.sizePolicy().hasHeightForWidth())
        transapiform.setSizePolicy(sizePolicy)
        transapiform.setMaximumSize(QSize(600, 400))
        v1 = QtWidgets.QVBoxLayout(transapiform)

        h1 = QtWidgets.QHBoxLayout()
        self.label = QLabel()
        self.label.setObjectName("label")
        self.label.setMinimumSize(QSize(150, 35))
        self.api_url = QLineEdit()
        self.api_url.setObjectName("api_url")
        self.api_url.setMinimumSize(QSize(0, 35))
        h1.addWidget(self.label)
        h1.addWidget(self.api_url)
        v1.addLayout(h1)

        h2 = QtWidgets.QHBoxLayout()
        self.label_3 = QLabel()
        self.label_3.setObjectName("miyue")
        self.label_3.setMinimumSize(QSize(150, 35))

        self.miyue = QLineEdit()
        self.miyue.setObjectName("miyue")
        h2.addWidget(self.label_3)
        h2.addWidget(self.miyue)
        v1.addLayout(h2)

        self.tips = QtWidgets.QPlainTextEdit()
        self.tips.setObjectName("tips")
        self.tips.setReadOnly(True)
        v1.addWidget(self.tips)

        h3 = QtWidgets.QHBoxLayout()
        self.save = QPushButton()
        self.save.setObjectName("save")
        self.save.setMinimumSize(QSize(0, 35))

        self.test = QPushButton(transapiform)
        self.test.setObjectName("test")
        self.test.setMinimumSize(QSize(0, 35))

        help_btn = QtWidgets.QPushButton()
        help_btn.setMinimumSize(QtCore.QSize(0, 35))
        help_btn.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        help_btn.setObjectName("help_btn")
        help_btn.setCursor(Qt.PointingHandCursor)
        help_btn.setText(tr("Fill out the tutorial"))
        help_btn.clicked.connect(lambda: open_url(url='https://pyvideotrans.com/transapi'))
        h3.addWidget(self.save)
        h3.addWidget(self.test)
        h3.addWidget(help_btn)

        v1.addLayout(h3)

        self.retranslateUi(transapiform)

        QMetaObject.connectSlotsByName(transapiform)

    # setupUi

    def retranslateUi(self, transapiform):
        tips = tr('transapi_help')
        transapiform.setWindowTitle(
            tr("Customizing the Translate API"))
        self.label_3.setText(tr("Secret"))
        self.miyue.setPlaceholderText(tr('Enter API key'))

        self.tips.setPlainText(tips)

        self.save.setText(tr("Save"))
        self.api_url.setPlaceholderText(
            tr("Fill in the full address starting with http"))
        self.label.setText(tr("Translate API"))
        self.test.setText(tr("Test"))
    # retranslateUi
